### ISSUE TITLE
errors on running sdaps on sample examples

### ISSUE THREAD

**Issue by berteh** [sdaps/sdaps#98]
hello.

I get errors I can't understand from running sdaps (fresh out of unstable repo) on Xubuntu (15.10) on the sample examples:

### parsing the odt-5/debug.odt leads to:
I downloaded https://github.com/sdaps/sdaps/raw/master/test/data/odt-5/debug.odt (tested odt-3/debug before, leading to same error)

```
$ sdaps /tmp/lta-sdaps setup --duplex --print-questionnaire-id --global-id=Test debug.odt debug.pdf
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Erreur : Caught an Exception while parsing the ODT file. The current state is:
Questionnaire
1.0(Head) Allgemeines
1.1(Choice) In welchem Studiengang bist Du immatrikuliert? {0}
(...)
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/setup.py", line 100, in setup
    return setupodt.setup(survey, cmdline['questionnaire.odt'], cmdline['questionnaire.pdf'], cmdline['additional_questions'], cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/setupodt/__init__.py", line 88, in setup
    qobjectsparser.parse(survey, questionnaire_odt, boxes)
  File "/usr/lib/python2.7/dist-packages/sdaps/setupodt/qobjectsparser.py", line 102, in parse
    xml.sax.parseString(content, handler)
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 49, in parseString
    parser.parse(inpsrc)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 317, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/lib/python2.7/dist-packages/sdaps/setupodt/qobjectsparser.py", line 66, in startElement
    self.answer.setup.box(self.boxes.pop(0))
IndexError: pop from empty list
```

### Testing TeX-way:

When testing  the tex way, creating the project structure and pdf runs as expected in tutorial, but adding answers images (http://sdaps.org/Documentation/Tutorial/example-2.tif) not:

```
$ sdaps /tmp/project add example-2.tif
------------------------------------------------------------------------------
- SDAPS -- add
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/script.py", line 105, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/add.py", line 125, in add
    print _('Processing %s') % file
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```

### More over
The install process went like a breeze: since packages only exist for trusty, add to software sources:

    deb http://ppa.launchpad.net/benjamin-sipsolutions/sdaps/ubuntu trusty main

then I ran

    sudo apt-get update
    sudo apt-get install spads
    
and done, about 1.2 Gb of additional librairies installed (incl. LaTeX).

**Comment by benzea** [comment]
With regard to the TeX issue:
 1. Could you run `locale` in your shell to see what language is set?
 2. Could you try running `LANG=C sdaps /tmp/project add example-2.tif` i.e. prefix the command with LANG=C to disable translations.

I am a bit unsure about the LO issue right now. It might be that I didn't push a new version into the PPA with the fixes for LibreOffice.

**Comment by berteh** [comment]
sure:

```
$ locale
LANG=fr_BE.UTF-8
LANGUAGE=fr_BE:fr
LC_CTYPE="fr_BE.UTF-8"
LC_NUMERIC="fr_BE.UTF-8"
LC_TIME="fr_BE.UTF-8"
LC_COLLATE="fr_BE.UTF-8"
LC_MONETARY="fr_BE.UTF-8"
LC_MESSAGES="fr_BE.UTF-8"
LC_PAPER="fr_BE.UTF-8"
LC_NAME="fr_BE.UTF-8"
LC_ADDRESS="fr_BE.UTF-8"
LC_TELEPHONE="fr_BE.UTF-8"
LC_MEASUREMENT="fr_BE.UTF-8"
LC_IDENTIFICATION="fr_BE.UTF-8"
LC_ALL=
```

running the ``sdaps add`` command with the prefix ``LANG=C`` makes no difference in my case, leading to the error described before.

I tried as well to remove the project directory and run ``sdaps setup_text`` with the same ``LANG=C`` prefix, and only then the ``add``, but with no luck neither.

I hacked quickly sdaps/log.py to temporarily fix this error... but am not confident this is the best way to handle the error, as it does not trace back the problem to its source... but only put a "bandaid" on top:

```
    def write(self, data):
		try:
			self.pipe.write(data.encode('utf-8'))
		except UnicodeDecodeError:
			self.pipe.write(data) 
```

Pull request coming, but feel free to trash it if you have a better way of fixing this problem.

**Comment by berteh** [comment]
with the fix above most commands in the LaTeX workflow from the tutorial seem to work fine... but for the ODT issue mentioned above.

**Comment by benzea** [comment]
Hm, I am a bit confused about which strings are unicode and wich ones are not.

So, we are writing a utf-8 string into the logging facility here. To encode it as utf-8 it gets decoded automatically and this fails because the IO character encoding isn't set?

In that case, the more correct way to handle it might be to only run the encode routine if a unicode string was passed in. Though the real question is, what is the right convention to use here (i.e. must a unicode string be passed if it may contain non-ascii characters?)

**Comment by benzea** [comment]
The above would mean that a more correct solution would be:

    if isinstance(data, unicode):
        self.pipe.write(data.encode('utf-8'))
    else:
        self.pipe.write(data)

Inside the encoder

**Comment by berteh** [comment]
much better fix, thanks. just tested, works fine.
shall I leave the issue open for the ODT problem? (but I won't look into this one, bit out of my reach and time).

**Comment by berteh** [comment]
fyi a short explanation as to why encoding an encoded string is an issue: http://stackoverflow.com/a/24475405

**Comment by benzea** [comment]
Hmm, I am thinking the ODT issue may have been fixed with the new release (i.e. you just tested against an old SDAPS version).

Closing for now. Please reopen if there still is an issue.

**Comment by rongmu** [comment]
I found that this issue persists with sdaps v1.9.1-1 in Ubuntu 16.04

```
$ sdaps q0 setup debug.odt debug.pdf
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Error: Caught an Exception while parsing the ODT file. The current state is:
Questionnaire
0(Head) Allgemeines
1(Choice) In welchem Studiengang bist Du immatrikuliert? {0}
2(Choice) In welchem Fachsemester bist Du? {0}

------------------------------------
If the dependencies for the "annotate" command are installed, then an annotated version will be created next to the original PDF file.
------------------------------------
/usr/lib/python2.7/dist-packages/sdaps/annotate/__init__.py:18: PyGIWarning: Poppler was imported without specifying a version first. Use gi.require_version('Poppler', '0.18') before import to ensure that the right version gets loaded.
  from gi.repository import Poppler
/usr/lib/python2.7/dist-packages/sdaps/annotate/buddies.py:21: PyGIWarning: Pango was imported without specifying a version first. Use gi.require_version('Pango', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Pango
/usr/lib/python2.7/dist-packages/sdaps/annotate/buddies.py:22: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/setup.py", line 100, in setup
    return setupodt.setup(survey, cmdline['questionnaire.odt'], cmdline['questionnaire.pdf'], cmdline['additional_questions'], cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/setupodt/__init__.py", line 88, in setup
    qobjectsparser.parse(survey, questionnaire_odt, boxes)
  File "/usr/lib/python2.7/dist-packages/sdaps/setupodt/qobjectsparser.py", line 103, in parse
    xml.sax.parseString(content, handler)
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 49, in parseString
    parser.parse(inpsrc)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 317, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/lib/python2.7/dist-packages/sdaps/setupodt/qobjectsparser.py", line 67, in startElement
    self.answer.setup.box(self.boxes.pop(0))
IndexError: pop from empty list
```

**Comment by benzea** [comment]
Odd, I am simply not seeing that issue here.

It sounds like the checkboxes have not been found in the PDF file. Did you use the downloaded PDF file or did you generate it in some other way?
